services:
  frontend:
    build:
      context: .
      args:
        - NUXT_PROXY_TARGET=http://host.docker.internal:80
        - NUXT_PUBLIC_MIDTRANS_CLIENT_KEY=${NUXT_PUBLIC_MIDTRANS_CLIENT_KEY}
    container_name: toko_frontend
    environment:
      - NUXT_PUBLIC_MIDTRANS_CLIENT_KEY=${NUXT_PUBLIC_MIDTRANS_CLIENT_KEY}
      - MIDTRANS_MERCHANT_ID=${MIDTRANS_MERCHANT_ID}
    ports:
      - "3000:3000"
    restart: unless-stopped
